# We want to make sure the Dockerfile does build an image & that the tests run
name: Test Docker & Run tests.py

on:
  push:
    branches: [ master ]

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
    - name: Run build.sh
      run: bash build.sh

    - name: Run pytest
      run: bash test.sh
